package com.tienda.view;
import MetodosDePago.*;
import Abstractas.Pago;
import Abstractas.Producto;
import Productos.Ropa;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ClienteFrame extends javax.swing.JFrame {
    /*DefaultTableModel:
    sirve como una estructura de datos flexible y predeterminada
    para gestionar el contenido de un componente JTable.*/
    DefaultTableModel modeloCatalogo;
    DefaultTableModel modeloCarrito;
    //esta lista recibe el catalogo de la tienda
    private List<Producto> catalogo;
    //esta lista guarda lo que el cliente selecciona
    private List<Producto> carritoCompras=  new ArrayList<>();
    private List<Producto> listaProductos;
    double totalCompra=0.0;
        
    public ClienteFrame(List<Producto>listaRecibida) {
        initComponents();
        this.catalogo=listaRecibida;
        configurarTablas();
        if(this.catalogo != null && !this.catalogo.isEmpty()){
            cargarCatalogoVisual();
            }
        }
    private void cargarCatalogoVisual(){
     if(catalogo==null) return;//evita error con la lista 
    //limpiamos la tabla
    modeloCatalogo.setRowCount(0);  
    //validacion de inventario
    for(Producto p: catalogo){    
    if (p.getstock()>0) { 
    modeloCatalogo.addRow(new Object[]{
    p.getId(), 
    p.getnombre(), 
    p.getprecio(), 
    p.getstock(), 
    p.getClass().getSimpleName()
    
            });
          }
        }
    }
        private void configurarTablas(){
        //Configuracion de la tabla del catologo
        modeloCatalogo=new DefaultTableModel();
        modeloCatalogo.addColumn("ID");
        modeloCatalogo.addColumn("Nombre");
        modeloCatalogo.addColumn("Precio");
        modeloCatalogo.addColumn("Tipo");
        /*setModel:
        vincula una estructura de datos (el modelo) al componente visual (la vista). Permite actualizar, cambiar
        o definir dinámicamente los datos que se muestran sin reconstruir el componente desde cer
        */
        tablaCatalogo.setModel(modeloCatalogo);
        //Configuracion de la tabla del carrito
        modeloCarrito= new DefaultTableModel();
        modeloCarrito.addColumn("Nombre");
        modeloCarrito.addColumn("Precio");
        tablaCarrito.setModel(modeloCarrito);
        
        cargarDatosPrueba();
    }
    private void cargarDatosPrueba() {
        if(this.catalogo==null||this.catalogo.isEmpty()){
            this.catalogo=new ArrayList<>();
        }
        catalogo.add(new Ropa(1, "Camisa Blanca", 45000, 10, "M", "Slim Fit"));
        catalogo.add(new Ropa(2, "Jean Azul", 85000, 5, "32", "Recto"));
        catalogo.add(new Ropa(3, "Chaqueta Cuero", 120000, 3, "L", "Casual"));
        cargarCatalogoVisual();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCatalogo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        txtTotal = new javax.swing.JLabel();
        cbMetodoPago = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarCarrito = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CATALOGO DE PRODUCTOS");

        tablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCatalogo);

        jLabel2.setText("CARRITO DE COMPRAS");

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaCarrito);

        txtTotal.setText("TOTAL: $ 0.0");

        cbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Transferencia" }));

        jLabel4.setText("Metodo de pago->");

        btnAgregarCarrito.setText("Agregar al Carrito");
        btnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarritoActionPerformed(evt);
            }
        });

        btnComprar.setText("Confirmar Compra");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComprar)))
                .addGap(350, 350, 350))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnComprar)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
        /*.getSelectedRow();
        sirve para obtener el índice (número) de la fila
        que el usuario ha seleccionado actualmente.
        */
        int filaSeleccionada=tablaCatalogo.getSelectedRow();
        if(filaSeleccionada>=0){
            //Obtencion de datos de la tabla
            String idTabla=tablaCatalogo.getValueAt(filaSeleccionada, 0).toString();
            for(Producto p: catalogo){
                if(String.valueOf(p.getId()).equals(idTabla)){
                   carritoCompras.add(p);
                   //Extraccion de datos de "p"
                   String nombre=p.getnombre();
                   double precio=p.getprecio();
                   //Agregamos esto a la tabla visual del carrito
                   modeloCarrito.addRow(new Object[]{nombre, precio});
                   //sumamos al total de la compra el precio de los productos
                   totalCompra+=precio;
                   //mostramos el total de la compra
                   txtTotal.setText("Total: $" + totalCompra);
                   JOptionPane.showMessageDialog(this, p.getnombre() + "Agregado al carrito");
                   break;
                   }
                }
                //hace que el usuario seleccione primero un producto al carrito antes de agregarlo
                }else{
            JOptionPane.showMessageDialog(this,"Por favor, selecciona un producto del catalogo primero");
        }

    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        /*.getRowCount():
         sirve para obtener el número total de filas (registros) presentes en un objeto de datos,
        como una tabla, un conjunto de resultados (ResultSet) o un modelo de tabla
        */
        if(modeloCarrito.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "El carrito esta vacio");
            return;
        }
        String metodo =cbMetodoPago.getSelectedItem().toString();
        /*
        Inicializamos la variable pago para usarla
        */
        Pago miPago=null;
        if(metodo.equals("Efectivo")){
            miPago=new pagoEfectivo(totalCompra, totalCompra);
        }else if(metodo.equals("Tarjeta")){
            miPago = new pagoTarjeta(totalCompra, "0000-0000-0000-0000", "Visa");
        }else{
            miPago = new pagoTransferencia(totalCompra, "REF-9999");
        }
        miPago.procesarPago();
        generarFacturaTexto();
        JOptionPane.showMessageDialog(this, "¡Compra realizada con éxito por $" + totalCompra + " usando " + metodo + "!");
        /*
        Limpiamos el carrito para una nueva compra
        */
        modeloCarrito.setRowCount(0);
        totalCompra = 0.0;
        txtTotal.setText("Total: $0.0");
    }//GEN-LAST:event_btnComprarActionPerformed
        private void generarFacturaTexto(){
        /*PrintWritter:
            See utiliza para escribir texto formateado, incluyendo tipos primitivos (int, float, 
            boolean), cadenas (String) y objetos, de manera sencilla en archivos, consolas o flujos de red
            */
        try (PrintWriter writer = new PrintWriter(new FileWriter("Factura_Compra.txt"))) {
            writer.println("======= FACTURA DE VENTA =======");
            writer.println("Fecha: " + new java.util.Date());
            writer.println("--------------------------------");
            for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            writer.println(modeloCarrito.getValueAt(i, 0) + " - $" + modeloCarrito.getValueAt(i, 1));
            }
        writer.println("--------------------------------");
        writer.println("TOTAL PAGADO: $" + totalCompra);
        writer.println("Metodo: " + cbMetodoPago.getSelectedItem());
        writer.println("================================");
        JOptionPane.showMessageDialog(this, "Factura generada como 'Factura_Compra.txt'");
        }catch (IOException e) {
        System.out.println("Error al crear factura: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                List<Producto> prueba=new ArrayList<>();
                new ClienteFrame(prueba).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnComprar;
    private javax.swing.JComboBox<String> cbMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTable tablaCatalogo;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
